apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-runner
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-runner
subjects:
- kind: ServiceAccount
  name: gitlab-runner
roleRef:
  kind: Role
  name: gitlab-runner
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-runner
rules:
- apiGroups: ["", "extensions", "apps", "batch"]
  resources: ["deployments", "replicasets", "pods", "services", "secrets", "serviceaccounts", "roles", "logs", "pods/log", "pods/exec", "pods/portforward", "events", "endpoints", "poddisruptionbudgets", "ingresses", "cronjobs", "jobs", "configmaps", "statefulsets"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: ["", "extensions", "apps", "batch"]
  resources: ["deployments",  "services", "configmaps", "statefulsets", "cronjobs", "jobs"]
  verbs: ["create", "update"]
- apiGroups: [""]
  resources: ["pods/exec","pods/logs","secrets", "pods", "pods/portforward", "configmaps"]
  verbs: ["create", "delete"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch", "patch", "create", "delete"]
- apiGroups: ["monitoring.coreos.com"]
  resources: ["prometheusrules", "servicemonitors"]
  verbs: ["get", "list", "watch", "patch", "create", "delete"]
